server {
    listen 80;
    server_name 3.27.246.229;

    root /var/www/umoviesbooking;
    index index.html;

    # Important for React Router (Prevents 404 on refresh)
    location / {
        try_files $uri $uri/ /index.html;
    }
}